### ISSUE TITLE
Illegal expression

### ISSUE THREAD

**Issue by marekmaskarinec** [vtereshkov/umka-lang#58] opened 2021-04-04 13:39 UTC
I'm getting this error: `(51, 66): Illegal expression`, although I think, I have it correctly.

Code:

```rust
 47   infs = []infc{ 
 48     infc {9, 0, 1000, fn() { player.magespeed = 0.08 }, inf {0, fn() { player.magespeed = 0.1 }}}, // slowdown
 49     infc {19, 10, 1000, fn() { player.magespeed = 0.12 }, inf {0, fn() { player.magespeed = 0.1 }}}, // speedup 
 50     infc {24, 20, 0, fn() { player.shieldend = global.t + 10000 }, inf {0, fn() {  }}}, // slowdown
 51     infc {29, 25, 0, fn() { player.hp = 10 }, inf {0, fn() { }}}, // health regen
 52   }
```

Here are the two structs:

```go
type inf = struct {
	end: int
	endfunc: fn()
}

type infc = struct {
	s: int
	b: int
	l: int
	do: fn()
	inf: inf
}
```

**Comment by marekmaskarinec** [comment] 2021-04-04 14:40
When I put it all in one line, it works.

**Comment by vtereshkov** [comment] 2021-04-04 15:00
The problem is that Umka cannot accept the comma at the end of line 51, since there is no expression after the comma. But if you remove it, an implicit semicolon will be inserted (like in Go), which is also an error. So the right way is to move the closing brace from line 52 to line 51.

**Comment by Mazdaywik** [comment] 2021-04-04 15:02
> So the right way is to move the closing brace from line 52 to line 51.

Or enable trailing comma after last array item.

**Comment by vtereshkov** [comment] 2021-04-04 15:13
@Mazdaywik this would mean treating a comma as a terminator rather than a separator. I think Go grammar is somewhat inconsistent in this respect. Punctuation marks are generally treated as terminators. However, in case of composite literals, they are separators, but with a special rule for a trailing comma:
```
LiteralValue  = "{" [ ElementList [ "," ] ] "}" .
ElementList   = KeyedElement { "," KeyedElement } .
```
In Umka they are always separators without any special rules:
```
structLiteral = "{" [[ident ":"] expr {"," [ident ":"] expr}] "}".
```
or, for example,
```
stmtList = stmt {";" stmt}.
```

**Comment by marekmaskarinec** [comment] 2021-04-04 15:17
> So the right way is to move the closing brace from line 52 to line 51.

That works. I thought I tried that before, but it seems like I left `,` there. Should I close this?

**Comment by vtereshkov** [comment] 2021-04-04 15:19
Yes, closing.

**Closed by vtereshkov** 2021-04-04 15:19 UTC
Labels: question
