### ISSUE TITLE
No MSVC++ build script

### ISSUE THREAD

**Issue by skaller** [vtereshkov/umka-lang#22] opened 2020-11-24 04:27 UTC
Is it expected this will build on MacOS and on Windows with MSVC++ with a suitable build script? I'm willing to help on this. I would like to embed umka in Felix as a standard component and have some specific tasks in mind for it, but it has to build with my build tools on all the platforms Felix supports: Linux (gcc and clang), MacOS (clang) and Windows (MSVC++), and, down the track, Apple iOS and Android.

Are there any weird features needed to implement anything?

**Comment by skaller** [comment] 2020-11-24 05:01
This appears to have worked on MacOS:
```
.POSIX:

SRC = src
CFLAGS = -fPIC -O3 -Wall -Wno-format-security
#LDFLAGS = -static-libgcc
LDFLAGS = 

BIN_OBJ = src/umka.o
LIB_OBJ = src/umka_api.o src/umka_common.o src/umka_compiler.o src/umka_const.o src/umka_decl.o src/umka_expr.o src/umka_gen.o src/umka_ident.o src/umka_lexer.o src/umka_runtime.o src/umka_stmt.o src/umka_types.o src/umka_vm.o

.PHONY: all clean
all: umka libumka.so
clean:
	rm -f umka libumka.so
	rm -f src/*.o

umka: $(BIN_OBJ) $(LIB_OBJ)
	$(CC) $(LDFLAGS) -o $@ $^ -lm

libumka.so: $(LIB_OBJ)
	#$(CC) $(LDFLAGS) -shared -fPIC -o libumka.so $^ -lm
	$(CC) $(LDFLAGS) -shared -fPIC -o libumka.dylib $^ 

src/%.o: src/%.c
```
and then
```
~/umka-lang>./umka tests/tour.um
```
produces some output. There is a `libumka.dylib` in the top level directory and I guess `src/umka_api.h` is the corresponding header file.?

The API fails to provide correct export visibility control, and there's no static archive (which I require also). Visibility control is mandatory and a real pain. There are two ways to do it, both are messy. On unix systems, one needs to compile with visibility hidden and then explicitly make the API available. On Windows you have to use adaptive macros that export the symbol when building the DLL, and import it otherwise.

**Comment by vtereshkov** [comment] 2020-11-24 10:34
@skaller Thank you for your interest in Umka. 

- If you wish to have a build script for MacOS, please make a pull request, and I will be happy to merge it provided that it doesn't break the existing code or infrastructure. 
- Unfortunately I cannot check Umka on MacOS myself. To be sure Umka is working properly, you can run `./umka tests/all.um > out.log` and take a `diff` with `tests/expected.log`. Only pointer values are allowed to be different. You can also run `./umka examples/raytracer.um` and see whether you get a correct `scene.ppm` image similar to `scene.png`. 
- The problem of export visibility control, if I understand you correctly, is about building the interpreter shared library, not about having some `public`/`private` keywords in Umka. If so, then this is indeed a mess. Are you going to try to do it yourself or you need my support? We could make a separate branch (or your own fork of the whole repository) for experimenting. Depending on the results, we could then discuss merging it to the `master` branch.

**Comment by skaller** [comment] 2020-11-24 11:57
I have MacOS, Linux, Windows, and iOS build capability. I'll run the tests. 

So a couple of points where I don't care for my use but other clients may:

* change the name of the unix makefile to GNUmakefile, unix make will use that in preference to Makefile. Windows nmake will work with Makefile.

* consider putting the install, configure, and test stuff in the makefiles, because that's traditional. 

* support both dynamic and static linkage if possible

This stuff is a pain, but I am considering making it part of the Felix core, which means I have to build it using the Felix build system. Another such product I use as core is Google RE2. Other packages I use, including SDL2, are considered external libraries (so the client has to obtain them: "not my problem").

**Comment by skaller** [comment] 2020-11-24 12:12
Ok, so I can do the visibility stuff for you. It involves adding a macro to the API functions like this:
```
void UML_EXTERN somefun();
```

The problem is now how to set the macro. There are two variables. One: are we compiling for static or dynamic link? Static link does not require visibility control. If we are compiling for dynamic link, then when the macro takes two different values, depending on whether we're building the Umka shared library, or using it. If building, the API symbols only must be exported, if using it, imported. On Unix, you must compile with `-fvisibility hidden` and the macro sets the API symbols to visibility `default`. This works like `extern` in that this value is correct for both export and import. On Windows, you have to set export building the DLL, and import when using it.

That's just a general description so I can explain the two methods of setting the macros.

Method 1 is is to provide compiler switches. You must set `-dUNKIA_STATIC` for static linking, and `-dUMKA_BUILD` when building the library, and fail to set them when dynamic linking or using (respectively). Then you can use conditional compilation to decide what to set `UMKA_EXTERN` to. This is what I do, I can show the exact code if you think this is best.

Method 2 achieves the same thing *without* any special compiler switches, instead, you put the macro settings in files, and then choose which file to compile. This method is seamless but it involves THREE header files instead of one, and TWO body files. I have done this for another repository. The seamless building means standard make like build scripts that don't know how to control visibility work out of the box on all platforms.

**Comment by skaller** [comment] 2020-11-24 12:24
In particular here is what I use:
```
#if FLX_WIN32
  #if defined(FLX_STATIC_LINK)
    #define FLX_EXPORT
    #define FLX_IMPORT
  #else
    #define FLX_EXPORT __declspec(dllexport)
    #define FLX_IMPORT __declspec(dllimport)
  #endif
#else
  // All modules on Unix are compiled with -fvisibility=hidden
  // All API symbols get visibility default
  // whether or not we're static linking or dynamic linking (with -fPIC)
  #define FLX_EXPORT __attribute__((visibility("default"))) 
  #define FLX_IMPORT __attribute__((visibility("default"))) 
#endif

#ifdef BUILD_RTL
#define RTL_EXTERN FLX_EXPORT
#else
#define RTL_EXTERN FLX_IMPORT
#endif
```

This is for building the Felix RTL (run time library core lib). Felix has other libraries, every library needs a unique macro name. You would use UMKA_EXTERN instead. The other `FLX` macros are the same for all libraries.

To make this work the compiler command line must define or not define `BUILD_RTL` and also `FLX_STATIC_LINK`.
The above script works on Linux, MacOS, and Windows. You need to include it in the API header file AND ensure that definitions as well as declarations have the EXTERN macro.

**Comment by vtereshkov** [comment] 2020-11-24 13:02
@skaller Thank you. This needs some time to grasp. But anyway, I would probably prefer method 1.

**Comment by vtereshkov** [comment] 2020-11-24 23:18
@skaller I have fixed a couple of minor inconsistencies, so it now compiles successfully under MSVC++, at least as a monolith application. The export visibility control problem is still valid, though.

**Comment by skaller** [comment] 2020-11-24 23:44
OK, method 1 then. The way forward I think is to (a) fix the source code first but not the scripts. Everything should still work as it does now, without visibility control. (b) Then fix the build scripts, one platform at a time. For the shared lib there are tools that show, in each platform, the exported symbols, `nm` on Linux I think or `otool` or something.

**Comment by skaller** [comment] 2020-11-26 05:44
ok so here's the diff:

[expected.txt](https://github.com/vtereshkov/umka-lang/files/5600721/expected.txt)

It's big. Hmm. Something's not right.

**Comment by vtereshkov** [comment] 2020-11-26 10:08
@skaller Thank you. Was it a 64-bit MacOS machine? I suppose the interpreter has passed the tests and all the differences are caused by
* Different memory addresses (this is a normal behavior).
* Different line endings (this is an unrelated problem, if problem at all. Anyway, I'll consider changing my Git settings).

**Comment by skaller** [comment] 2020-11-26 13:20
MacOS does not support 32 bit any more. Soon Apple Silicon is out, that's an ARM64 machine. Apple will not be making any more Intel devices. 

I agree all tests passed. Step by step we'll get the visibility done. I have to say I hate using clone/pull request. Too hard to keep the repositories in sync. Confusing: I'll need two local repos, one from master and one being the clone. I need to first test the Felix binding with the clone, then replace the clone with the master. I strongly prefer to use a direct image of the master repository in Felix library add-ons otherwise the version gets pinned and can't be upgraded.

I need to look at the API to see if it will do what I want. I haven't looked at any code yet. Was impressed enough by the system that I'm just assuming it will either work or be fixable. What I'm thinking of doing is this (just FYI):

Felix compiler generates RTTI objects which tell the GC where all the pointers are in a type, how to serialise and deserialise it, how to copy it, etc. These can be considered "metatype" objects. Now suppose you want to create a new type at run time, you need to construct a suitable meta type RTTI object. In particular if the type is a product of several other types there's a mechanical formula for combining them to produce suitable RTTI object. In other case the type is some new custom type and needs a custom generated RTTI object. 

This is dynamic meta-typing (not dynamic typing). The underlying system remains strongly statically typed. The reason for doing this is as follows: in languages like Haskell, by using boxing, you can write routines that work for any type at run time. In Felix, I do not want to use boxing, but use a RTTI descriptor instead, which allows the type to be unboxed, but we can still  write a routine that works with any type.

That's the first job I am thinking of for Umka. To enable second order polymorphism.

**Comment by vtereshkov** [comment] 2020-11-27 13:09
I've checked your pull request on Linux. It failed:
```
vtereshkov@vtereshkov-ubuntupc:~/umka-lang$ make
cc -fPIC -O3 -Wall -Wno-format-security -DUMKA_STATIC -c -o src/umka_api_static.o src/umka_api.c
cc -fPIC -O3 -Wall -Wno-format-security -DUMKA_STATIC -c -o src/umka_common_static.o src/umka_common.c
cc -fPIC -O3 -Wall -Wno-format-security -DUMKA_STATIC -c -o src/umka_compiler_static.o src/umka_compiler.c
cc -fPIC -O3 -Wall -Wno-format-security -DUMKA_STATIC -c -o src/umka_const_static.o src/umka_const.c
cc -fPIC -O3 -Wall -Wno-format-security -DUMKA_STATIC -c -o src/umka_decl_static.o src/umka_decl.c
cc -fPIC -O3 -Wall -Wno-format-security -DUMKA_STATIC -c -o src/umka_expr_static.o src/umka_expr.c
cc -fPIC -O3 -Wall -Wno-format-security -DUMKA_STATIC -c -o src/umka_gen_static.o src/umka_gen.c
cc -fPIC -O3 -Wall -Wno-format-security -DUMKA_STATIC -c -o src/umka_ident_static.o src/umka_ident.c
cc -fPIC -O3 -Wall -Wno-format-security -DUMKA_STATIC -c -o src/umka_lexer_static.o src/umka_lexer.c
cc -fPIC -O3 -Wall -Wno-format-security -DUMKA_STATIC -c -o src/umka_runtime_static.o src/umka_runtime.c
cc -fPIC -O3 -Wall -Wno-format-security -DUMKA_STATIC -c -o src/umka_stmt_static.o src/umka_stmt.c
cc -fPIC -O3 -Wall -Wno-format-security -DUMKA_STATIC -c -o src/umka_types_static.o src/umka_types.c
cc -fPIC -O3 -Wall -Wno-format-security -DUMKA_STATIC -c -o src/umka_vm_static.o src/umka_vm.c
# Build static archive 
ar -c -static-libgcc -o libumka.a src/umka_api_static.o src/umka_common_static.o src/umka_compiler_static.o src/umka_const_static.o src/umka_decl_static.o src/umka_expr_static.o src/umka_gen_static.o src/umka_ident_static.o src/umka_lexer_static.o src/umka_runtime_static.o src/umka_stmt_static.o src/umka_types_static.o src/umka_vm_static.o
ar: two different operation options specified
GNUmakefile:41: recipe for target 'libumka.a' failed
make: *** [libumka.a] Error 1
```

**Comment by skaller** [comment] 2020-11-27 14:12
So it's fixed I think. I can't easily check on Linux. I tried ar -rs on MacOS and that works.

**Comment by vtereshkov** [comment] 2020-11-27 15:34
It still fails, but at some other step. Anyway, for me this is not urgent. If the existing version works fine on MacOS and is sufficient for you to start experimenting with your metatypes in Felix, we can fix the Linux build later. If you could, please make your new pull requests directly to the `visibility-control` branch where I have already merged your pull requests.
```
vtereshkov@vtereshkov-ubuntupc:~/umka-lang$ make
cc -fPIC -O3 -Wall -Wno-format-security -DUMKA_STATIC -c -o src/umka_api_static.o src/umka_api.c
cc -fPIC -O3 -Wall -Wno-format-security -DUMKA_STATIC -c -o src/umka_common_static.o src/umka_common.c
cc -fPIC -O3 -Wall -Wno-format-security -DUMKA_STATIC -c -o src/umka_compiler_static.o src/umka_compiler.c
cc -fPIC -O3 -Wall -Wno-format-security -DUMKA_STATIC -c -o src/umka_const_static.o src/umka_const.c
cc -fPIC -O3 -Wall -Wno-format-security -DUMKA_STATIC -c -o src/umka_decl_static.o src/umka_decl.c
cc -fPIC -O3 -Wall -Wno-format-security -DUMKA_STATIC -c -o src/umka_expr_static.o src/umka_expr.c
cc -fPIC -O3 -Wall -Wno-format-security -DUMKA_STATIC -c -o src/umka_gen_static.o src/umka_gen.c
cc -fPIC -O3 -Wall -Wno-format-security -DUMKA_STATIC -c -o src/umka_ident_static.o src/umka_ident.c
cc -fPIC -O3 -Wall -Wno-format-security -DUMKA_STATIC -c -o src/umka_lexer_static.o src/umka_lexer.c
cc -fPIC -O3 -Wall -Wno-format-security -DUMKA_STATIC -c -o src/umka_runtime_static.o src/umka_runtime.c
cc -fPIC -O3 -Wall -Wno-format-security -DUMKA_STATIC -c -o src/umka_stmt_static.o src/umka_stmt.c
cc -fPIC -O3 -Wall -Wno-format-security -DUMKA_STATIC -c -o src/umka_types_static.o src/umka_types.c
cc -fPIC -O3 -Wall -Wno-format-security -DUMKA_STATIC -c -o src/umka_vm_static.o src/umka_vm.c
# Build static archive 
ar -c -rs  libumka.a src/umka_api_static.o src/umka_common_static.o src/umka_compiler_static.o src/umka_const_static.o src/umka_decl_static.o src/umka_expr_static.o src/umka_gen_static.o src/umka_ident_static.o src/umka_lexer_static.o src/umka_runtime_static.o src/umka_stmt_static.o src/umka_types_static.o src/umka_vm_static.o
cc -fPIC -O3 -Wall -Wno-format-security -DUMKA_STATIC -c -o src/umka_static.o src/umka.c
# Build executable 
cc -fPIC -O3 -Wall -Wno-format-security -DUMKA_STATIC -o umka libumka.a src/umka_static.o
src/umka_static.o: In function `main':
umka.c:(.text.startup+0xc5): undefined reference to `umkaAlloc'
umka.c:(.text.startup+0xe2): undefined reference to `umkaInit'
umka.c:(.text.startup+0xfa): undefined reference to `umkaGetError'
umka.c:(.text.startup+0x12e): undefined reference to `umkaFree'
umka.c:(.text.startup+0x198): undefined reference to `umkaCompile'
umka.c:(.text.startup+0x1c1): undefined reference to `umkaAsm'
umka.c:(.text.startup+0x23c): undefined reference to `umkaRun'
umka.c:(.text.startup+0x248): undefined reference to `umkaFree'
umka.c:(.text.startup+0x288): undefined reference to `umkaGetError'
collect2: error: ld returned 1 exit status
GNUmakefile:49: recipe for target 'umka' failed
make: *** [umka] Error 1
```

**Comment by skaller** [comment] 2020-11-27 21:59
I don't know why this failed. Its saying the library `libumka.a` doesn't have any symbols in it. Surely you can fix this? Try running the `ar` command without removing the `-c`?

I very much do not want to build core Felix stuff on any library than your master. The binding is only 10 minutes work. However I really have no idea how to interface umka yet and there aren't any docs on that. Umka scripts need to be able to access external data structures and call external functions (like `malloc()`). I've looked at the VM briefly.

**Comment by vtereshkov** [comment] 2020-11-27 22:40
@skaller The Umka API is briefly documented [here](https://github.com/vtereshkov/umka-lang/blob/master/spec.md#embedding-api). An example of C/Umka integration is [here](https://github.com/vtereshkov/umka-lang/blob/master/examples/3dcam.c) and [here](https://github.com/vtereshkov/umka-lang/blob/master/examples/3dcam.um). If you want do build it, the instruction for Windows and Linux users is [here](https://github.com/vtereshkov/umka-lang/issues/8#issuecomment-656081532).

As you can see, Umka can call a C function, but not _every_ C function. Your function will probably have to be wrapped into another function with the required signature. This is the same approach as used in, e.g., Lua. An Umka function can also be called from C.

I think we cannot merge the code into `master` while it is broken on Linux (and the Windows build is not tested at all).

**Comment by skaller** [comment] 2020-11-27 23:51
I agree the code has to work on Linux. But you can fix it easily, I can't. I do have a Linux box but it is powered down, and a pain to get running again. I'll try, but i cannot test anything on Linux at the moment.

**Comment by skaller** [comment] 2020-11-28 00:05
So thanks for the API docs! Sorry I must have forgotten them.

At the moment, `umkaInit` takes a file name. This is not so useful. It needs to take a string. The client can load a file into a string in C. Perhaps you can add an API `umkaInitFromString`?

[Also you're API is not re-entrant. Perhaps it doesn't matter considering it is so lightweight.]

**Comment by vtereshkov** [comment] 2020-11-28 00:16
@skaller Yes, in the nearest future I will implement reading a script from a string buffer. This is indeed a useful thing and, in contrast with the visibility control (of which I'm still not sure), it will be definitely merged into `master` as soon as possible.

And what makes you think the API is not re-entrant? (I don't assert the opposite. Just curious).

**Comment by skaller** [comment] 2020-11-28 02:01
Any function that modifies the state of the interpreter implies non-reentrancy. For example the `init` function which loads a file or more pointedly the error retrieval. This is like Posix error handling via `errno`, the biggest disaster in programming language history. `strtok` is another such function. In fact C and C++ stdin/out are another disaster.

As I said it probably doesn't matter for Umka since its easy to create hopefully independent interpreters. This would only be an issue if some global storage were used. I haven't checked. Curious, is there any global (as in C extern or static) data?

**Comment by skaller** [comment] 2020-11-28 02:12
This is what I get on the Mac for the archive symbols using the Linux commands:

```
~/gitforks/umka-lang>ar -c -rs  libumka.a src/umka_api_static.o src/umka_common_static.o src/umka_compiler_static.o src/umka_const_static.o src/umka_decl_static.o src/umka_expr_static.o src/umka_gen_static.o src/umka_ident_static.o src/umka_lexer_static.o src/umka_runtime_static.o src/umka_stmt_static.o src/umka_types_static.o src/umka_vm_static.o
~/gitforks/umka-lang>echo $?
0
~/gitforks/umka-lang>nm -g -U libumka.a | grep umka*
libumka.a(umka_api_static.o):
00000000000003e0 T _umkaAddFunc
0000000000000000 T _umkaAlloc
00000000000003d0 T _umkaAsm
00000000000002f0 T _umkaCall
0000000000000270 T _umkaCompile
0000000000000350 T _umkaFree
0000000000000370 T _umkaGetError
0000000000000400 T _umkaGetFunc
0000000000000010 T _umkaInit
00000000000002b0 T _umkaRun
```
and then
```
~/gitforks/umka-lang>cc -fPIC -O3 -Wall -Wno-format-security -DUMKA_STATIC -o umka libumka.a src/umka_static.o
~/gitforks/umka-lang>echo $?
0
~/gitforks/umka-lang>./umka
Umka interpreter (C) Vasiliy Tereshkov, 2020
Usage: umka <file.um> [<parameters>] [<script-parameters>]
Parameters:
    -storage <storage-size>
    -stack   <stack-size>
    -asm     <output.asm>
```

So there is a small difference. I think the `-c` is wrong in the `ar` command. Please try manually to build the archive file and link against it.

**Comment by skaller** [comment] 2020-11-28 02:19
Here is why the visibility control is mandatory and more important than anything else: without it, there is a risk of conflicts. This means static linkage (which has no visibility control) will be useless, but that's true on modern systems anyhow. Windows more or less will not support static linkage and neither will MacOS. Linux as usual is lagging behind the rest of the world. 

Here are all the external symbols in the library, without visibility control, if you want to continue to support static linkage at all, you MUST change the names of every symbol so it is unique to `umka`, usually by putting `umka_` prefix in front of every symbol. This is not necessary for shared libraries provided they're built with visibility control.

The risk of clash may seem small and probably is, however, if there *is* a clash between two third party libraries the developer is completely screwed. It' standard practice in C to add a prefix. In C++ there are namespaces and name mangling so there are other ways.

```
~/gitforks/umka-lang>nm -g -U libumka.a

libumka.a(umka_api_static.o):
00000000000003e0 T _umkaAddFunc
0000000000000000 T _umkaAlloc
00000000000003d0 T _umkaAsm
00000000000002f0 T _umkaCall
0000000000000270 T _umkaCompile
0000000000000350 T _umkaFree
0000000000000370 T _umkaGetError
0000000000000400 T _umkaGetFunc
0000000000000010 T _umkaInit
00000000000002b0 T _umkaRun

libumka.a(umka_common_static.o):
00000000000007e0 T _blocksCurrent
0000000000000720 T _blocksEnter
0000000000000790 T _blocksFree
00000000000006e0 T _blocksInit
00000000000007a0 T _blocksLeave
00000000000008e0 T _externalAdd
0000000000000850 T _externalFind
0000000000000820 T _externalFree
0000000000000800 T _externalInit
0000000000000320 T _moduleAdd
0000000000000170 T _moduleAssertFind
00000000000000b0 T _moduleFind
0000000000000260 T _moduleFindByPath
0000000000000070 T _moduleFree
0000000000000040 T _moduleInit
0000000000000030 T _storageFree
0000000000000000 T _storageInit

libumka.a(umka_compiler_static.o):
0000000000000b70 T _compilerAsm
0000000000000b10 T _compilerCall
0000000000000ac0 T _compilerCompile
0000000000000a30 T _compilerFree
0000000000000b90 T _compilerGetFunc
0000000000000000 T _compilerInit
0000000000000ad0 T _compilerRun

libumka.a(umka_const_static.o):
0000000000000140 T _constAssign
0000000000000410 T _constBinary
0000000000000860 T _constCallBuiltin
0000000000000030 T _constDeref
0000000000000010 T _constFree
0000000000000000 T _constInit
00000000000003b0 T _constUnary
0000000000000020 T _constZero

libumka.a(umka_decl_static.o):
00000000000009c0 T _parseDecl
0000000000000f10 T _parseProgram
0000000000000880 T _parseShortVarDecl
0000000000000000 T _parseType

libumka.a(umka_expr_static.o):
00000000000008d0 T _doApplyOperator
0000000000000060 T _doImplicitTypeConv
0000000000000000 T _doPushConst
0000000000000030 T _doPushVarPtr
0000000000000b10 T _parseDesignator
0000000000002610 T _parseDesignatorList
0000000000002730 T _parseExpr
0000000000002c10 T _parseExprList
0000000000000a70 T _parseQualIdent

libumka.a(umka_gen_static.o):
0000000000003890 T _genAsm
0000000000001330 T _genAssertType
0000000000000a40 T _genAssign
0000000000000f60 T _genBinary
0000000000001510 T _genCall
0000000000001650 T _genCallBuiltin
00000000000015b0 T _genCallExtern
0000000000002630 T _genCaseBlockEpilog
0000000000002440 T _genCaseBlockProlog
00000000000020e0 T _genCaseExprEpilog
0000000000000c10 T _genChangeRefCnt
0000000000000cd0 T _genChangeRefCntAssign
0000000000000930 T _genDeref
0000000000000770 T _genDup
0000000000001cf0 T _genElseProlog
00000000000017d0 T _genEnterFrame
0000000000003370 T _genEnterFrameStub
00000000000035c0 T _genEntryPoint
0000000000002a40 T _genForCondEpilog
0000000000002a20 T _genForCondProlog
0000000000002d10 T _genForEpilog
0000000000002ba0 T _genForPostStmtEpilog
0000000000000080 T _genFree
0000000000001020 T _genGetArrayPtr
00000000000011a0 T _genGetDynArrayPtr
0000000000001280 T _genGetFieldPtr
0000000000001a30 T _genGoFromTo
0000000000001ae0 T _genGoFromToIf
00000000000013d0 T _genGoto
0000000000001470 T _genGotoIf
00000000000036a0 T _genGotosAddStub
0000000000003790 T _genGotosEpilog
0000000000003680 T _genGotosProlog
0000000000001950 T _genHalt
0000000000001b90 T _genIfCondEpilog
0000000000001e60 T _genIfElseEpilog
0000000000000000 T _genInit
0000000000001870 T _genLeaveFrame
0000000000003440 T _genLeaveFrameFixup
0000000000000090 T _genNop
00000000000005a0 T _genPop
00000000000006d0 T _genPopReg
0000000000000320 T _genPushGlobalPtr
0000000000000140 T _genPushIntConst
00000000000003c0 T _genPushLocalPtr
0000000000000280 T _genPushRealConst
0000000000000460 T _genPushReg
0000000000000500 T _genPushStruct
00000000000001e0 T _genPushUIntConst
0000000000001730 T _genReturn
00000000000031a0 T _genShortCircuitEpilog
0000000000002e60 T _genShortCircuitProlog
0000000000000850 T _genSwap
0000000000000af0 T _genSwapAssign
0000000000000de0 T _genSwapChangeRefCntAssign
0000000000001f20 T _genSwitchCondEpilog
00000000000027a0 T _genSwitchEpilog
0000000000000eb0 T _genUnary
00000000000028b0 T _genWhileCondEpilog
0000000000002890 T _genWhileCondProlog
00000000000028c0 T _genWhileEpilog

libumka.a(umka_ident_static.o):
0000000000000710 T _identAddBuiltinFunc
00000000000003a0 T _identAddConst
0000000000000680 T _identAddGlobalVar
00000000000006b0 T _identAddLocalVar
00000000000006e0 T _identAddType
00000000000008a0 T _identAllocParam
0000000000000740 T _identAllocStack
0000000000000790 T _identAllocVar
0000000000000350 T _identAssertFind
00000000000000b0 T _identFind
0000000000000020 T _identFree
0000000000000000 T _identInit
0000000000000930 T _identTempVarName

libumka.a(umka_lexer_static.o):
00000000000015c0 T _lexCheck
0000000000001630 T _lexEat
0000000000000210 T _lexFree
0000000000000000 T _lexInit
0000000000000240 T _lexNext
00000000000016c0 T _lexShortAssignment
0000000000001610 T _lexSpelling

libumka.a(umka_runtime_static.o):
0000000000000020 T _rtlfclose
0000000000000000 T _rtlfopen
0000000000000040 T _rtlfread
00000000000000a0 T _rtlfseek
0000000000000070 T _rtlfwrite
00000000000000e0 T _rtlremove
0000000000000100 T _rtltime

libumka.a(umka_stmt_static.o):
0000000000000000 T _doResolveExtern
0000000000000250 T _parseAssignmentStmt
00000000000006a0 T _parseDeclAssignmentStmt
0000000000000a20 T _parseFnBlock
0000000000000de0 T _parseFnPrototype

libumka.a(umka_types_static.o):
0000000000000180 T _typeAdd
0000000000000e90 T _typeAddField
0000000000001200 T _typeAddParam
0000000000000350 T _typeAddPtrTo
0000000000000930 T _typeAssertCompatible
00000000000007f0 T _typeAssertEquivalent
0000000000000db0 T _typeAssertFindField
0000000000000c80 T _typeAssertForwardResolved
0000000000000be0 T _typeAssertValidOperator
00000000000008a0 T _typeCompatible
0000000000000220 T _typeDeepCopy
0000000000000610 T _typeEquivalent
0000000000000ce0 T _typeFindField
0000000000001140 T _typeFindParam
0000000000000090 T _typeFree
0000000000000020 T _typeFreeFieldsAndParams
0000000000000590 T _typeGarbageCollected
0000000000000000 T _typeInit
00000000000015c0 T _typeKindSpelling
00000000000014b0 T _typeParamSizeTotal
00000000000013a0 T _typeParamSizeUpTo
00000000000004f0 T _typeSize
00000000000003e0 T _typeSizeNoCheck
0000000000000580 T _typeSpelling
0000000000000a50 T _typeValidOperator

libumka.a(umka_vm_static.o):
0000000000001fa0 T _vmAsm
0000000000000070 T _vmFree
0000000000000000 T _vmInit
00000000000000f0 T _vmReset
0000000000000120 T _vmRun
```

**Comment by skaller** [comment] 2020-11-28 07:00
FYI: Github actions provides a windows server with MSYS2. I will try to set that up to work as well, but I haven't used MSYS for decades. Funny thing is, Visual Studio tools MSVC++ do not seem to be available. Weird considering Microsoft owns Github and the CI services run on Microsoft Azure.

Note, for a Windows DLL visibility control is utterly and completely mandatory. This is because the compiler actions on creating exports in the library, and the compiler actions using those exported symbols from clients of the library, are quite different (even the machine instructions are different as well as the actions on the symbol table). Windows has used two level namespaces with visibility control for ever, because the core Windows linker actually does not support any kind of dynamic linkage! Calls to imported symbols are secretly changed from direct calls to indirect calls by the compiler, the indirect calls go via a thunk. The thunk is inside a `filename.lib` file corresponding to the `filename.dll` file, the lib file is actually statically linked, and calling it jumps to the entry point in the DLL at run time (after finding out at run time where that actually is).

Note this only for DLLs. But Windows insists on using DLLs, static linkage is generally not allowed, in particular if a DLL and another DLL or the executable both statically link to the C run time, you get two copies of the standard I/O buffers.

**Comment by vtereshkov** [comment] 2020-11-28 13:12
@skaller I have partially accepted your proposal on the export visibility control. Now it is on the `master` branch. I will consider Makefile issues separately.

**Comment by skaller** [comment] 2020-11-28 14:05
I am working on a full build for Linux, MacOS, MSYS2, and MSVC.

**Comment by skaller** [comment] 2020-11-28 14:27
OK its done for Linux, MacOS, MSYS64. There's a stub for MSVC.
Every push of the repo will automatically build all all these platforms using Github Actions.

There is one change you have to make. The badge added to the README points at my fork, you will need to manually change that.  There's no way at the moment to make the badge relative to the current repository.

**Comment by skaller** [comment] 2020-11-28 14:41
Having done all this I am disgusted by the OS detection stuff. What I implemented in the GNUmakefile works on the platforms Github Actions provides. B.ut it may be an idea to change the filename to `GithubActions.mak` and then change the `.github/workflows/main.yml` to say `make -f GithubActions.mak all`. This leaves the user without a makefile, which may be better than leaving the user with one that doesn't work, Perhaps the right way is to *force* the user to say this:
```
PLATFORM=Linux make all
```
so that we can be sure of the platform name. The build system I use is written in Python and took over a year to develop, and it doesn't always work right either :-)

**Closed** 2021-07-17 00:34 UTC
Labels: enhancement
