### ISSUE TITLE
Memory leak warnings when using fibers

### ISSUE THREAD

**Issue by luauser32167** [vtereshkov/umka-lang#255] opened 2022-12-13 13:55 UTC
```Go
type Ctx = struct {
  parent: fiber;
  cond: int;
  err: str;
  sum: int;
}

fn (ctx: ^Ctx) error(err: str) {
  ctx.err = err;
  fibercall(ctx.parent);
}

fn f1(ctx: ^Ctx): int {
  if 1 == ctx.cond {
    ctx.error("f1");
  }
  printf("f1()\n");
  return 1;
}

fn f2(ctx: ^Ctx): int {
  if 2 == ctx.cond {
    ctx.error("f2");
  }
  printf("f2()\n");
  return 2;
}

fn f3(ctx: ^Ctx): int {
  if 3 == ctx.cond {
    ctx.error("f3");
  }
  printf("f3()\n");
  return 3;
}

fn doStuffFib(parent: fiber, ctx: ^Ctx) {
  ctx.parent = parent;
  ctx.sum += f1(ctx);
  ctx.sum += f2(ctx);
  ctx.sum += f3(ctx);
}

fn (ctx: ^Ctx) doStuff(): (int, str) {
  fibercall(fiberspawn(doStuffFib, ctx));
  return ctx.sum, ctx.err;
}

var ctx: Ctx; // why do we get a memory leak warning when 'ctx' is declared as a global and we get an error (ctx.cond == 1|2|3)?

fn main() {
  // var ctx: Ctx; // why do we get a runtime error when 'ctx' is declared on the stack and we get an error (ctx.cond == 1|2|3)?
  // var ctx: ^Ctx = new(Ctx); // why do we get a memory leak warning when 'ctx' is allocated with 'new' and we get an error (ctx.cond == 1|2|3)?
  ctx.cond = 2;
  var sum: int;
  var err: str;
  sum, err = ctx.doStuff();
  if "" != err {
    printf("error: %s\n", err);
  } else {
    printf("sum: %d\n", sum);
  }
}
```

**Comment by vtereshkov** [comment] 2022-12-13 15:52
@luauser32167 This is actually a duplicate of #16. However, it's interesting to see how this issue interferes with the escape analysis when you allocate `ctx` on the stack.

**Comment by vtereshkov** [comment] 2022-12-17 11:27
Closing as duplicate of #16.

**Closed by vtereshkov** 2022-12-17 11:27 UTC
Labels: bug
