### ISSUE TITLE
Strings library.

### ISSUE THREAD

**Issue by skejeton** [vtereshkov/umka-lang#218] opened 2022-09-28 18:03 UTC
There seems to be a demand for a builtin strings library, currently we have utf8, which can be included there, but another thing we need is common string and character operations, specifically things like split, join, find, etc. For character operations, isspace and isprint, isalnum and isdigit seem to occur a lot in my projects, especially ones involving parsing.

**Comment by vtereshkov** [comment] 2022-09-28 20:25
Duplicate of #157.

**Closed by vtereshkov** 2022-09-28 20:25 UTC

**Comment by skejeton** [comment] 2022-09-29 09:26
Ah! Sorry my brain is melting
